// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL ?? "").trim().replace(/\/+$/, "") || undefined;
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "").trim() || undefined;

// Ak .env chýba (napr. pri lokálnom dizajnovom náhľade), nepadni pri štarte –
// použijeme neškodný placeholder, aby sa web zobrazil. Auth funkcie budú
// fungovať až po doplnení reálnych VITE_SUPABASE_* kľúčov do .env.
const isConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isConfigured) {
  // eslint-disable-next-line no-console
  console.warn(
    '[supabase] VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY nie sú nastavené. ' +
      'Web beží v ukážkovom režime – prihlásenie a platby budú neaktívne, kým nedoplníš .env.'
  );
}

export const supabaseConfigured = isConfigured;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'public-anon-placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
